site_name: Nixware API
nav:
    - Home: index.md
    - ui: ui.md
    - client: client.md
    - renderer: renderer.md
    - types:
      - vec2_t: types/vec2_t.md
      - vec3_t: types/vec3_t.md
      - angle_t: types/angle_t.md
      - rect_t: types/rect_t.md
      - color_t: types/color_t.md
    - source engine:
      - types:
        - game_event_t: sourceengine/types/game_event_t.md
        - usercmd_t: sourceengine/types/usercmd_t.md
        - convar_t: sourceengine/types/convar_t.md
        - entity_t: sourceengine/types/entity_t.md
        - player_info_t: sourceengine/types/player_info_t.md
        - shot_info_t - csgo: sourceengine/types/shot_info_t.md
      - ragebot - csgo: sourceengine/ragebot.md
      - se: sourceengine/se.md
      - engine: sourceengine/engine.md
      - trace: sourceengine/trace.md
      - entitylist: sourceengine/entitylist.md
      - globalvars: sourceengine/globalvars.md
      - clientstate: sourceengine/clientstate.md
    - callbacks: callbacks.md
theme:
  logo: https://nixware.cc/styles/default/xenforo/ava.png
  name: material
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition